### ISSUE TITLE
Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames

### ISSUE THREAD

**Issue by Aghiad90** [binafy/laravel-user-monitoring#15]
Hello , 
When adding use Actionable; to a model this error will appear 

![image](https://github.com/binafy/laravel-user-monitoring/assets/23388761/785e8e99-091c-4e12-8729-e3845cd26a46)

![image](https://github.com/binafy/laravel-user-monitoring/assets/23388761/f9e45894-4057-48ca-8594-e0c12f3c2c9d)

**Comment by OysteinHoiby** [comment]
Do you get this error on all models? 

For me this happens when I try to add Actionable to the User model, however on other models there's no trouble.

**Comment by Aghiad90** [comment]
> Do you get this error on all models?
> 
> For me this happens when I try to add Actionable to the User model, however on other models there's no trouble.

honestly have not tried to add it to a different model I will try it soon thank you for your reply

**Comment by milwad-dev** [comment]
Hello, sorry about my late for reply💙
We are using this package for a big project and other projects and `Actionable` worked successfully!
However, I'll check again, Thanks for making an issue :)
