### ISSUE TITLE
Package have many bugs

### ISSUE THREAD

**Issue by jastranlove2020** [binafy/laravel-user-monitoring#18]
- Missing Bootstrap paing
- Views are not working from the resources/view
- Missing middleware, anyone can view the routes.

It should be tested fully before suggesting to community. Takes much time to override routes

**Comment by milwad-dev** [comment]
1. If you want to use `Bootstrap`, you can customize the views!
2. The new version will be fixed
3. Publish middleware added => https://github.com/binafy/laravel-user-monitoring/pull/19
