### ISSUE TITLE
Route file and middleware with problems

### ISSUE THREAD

**Issue by GuilhermeGodzicki** [binafy/laravel-user-monitoring#23]
The route or middleware files are not being downloaded with the project when running composer, when trying to publish them it does not find the files, and looking in the downloaded folder in the project they do not exist.

**Comment by milwad-dev** [comment]
In the next version, you will be able to publish the route!
Do you say publish middleware, routes, and ... automatically?

**Comment by GuilhermeGodzicki** [comment]
No, I have already run composer install and update, to download the package requirements, when trying to publish the route and middleware files manually, they do not exist in the project that is being downloaded by composer, including the new files that should be in the src of the file, It seems as if the file he is downloading in composer is not the updated git project, even in composer lock it is showing that it is in version 1.0 just like in git

**Comment by GuilhermeGodzicki** [comment]
For example, I try to run php artisan vendor:publish --tag="laravel-user-monitoring-routes" and it even gives an error because it says that this file does not exist to be published, and when consulting the folder where this file was supposed to be The same file does not exist.

**Comment by milwad-dev** [comment]
Ohh I said before, you can publish route and middleware in the new version of `Laravel-User-Monitoring`.
The new version will be published next week

**Comment by milwad-dev** [comment]
Also, you can download the dev version!
