### ISSUE TITLE
Feature request: display custom user attribute instead of only name

### ISSUE THREAD

**Issue by elia-c** [binafy/laravel-user-monitoring#24]
Add a config option like `user\display_attribute` = 'display_name'
to use to display instead of only the user name.

With this feature will be possible to do something like append model attribute and use it. Example
```
class User extends Authenticatable
{
 /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['displaylabel'];

    /**
     * Attributo composto
     * @return string
     */
    public function getDisplaylabelAttribute()
    {
        return $this->name . ' ' . $this->surname;
    }

}
```

**Comment by milwad-dev** [comment]
Hello, This feature will be added soon.
Thanks for making an issue

**Comment by milwad-dev** [comment]
https://github.com/binafy/laravel-user-monitoring/pull/44
