### ISSUE TITLE
Packagist v1.0 is not the same as the github 1.0

### ISSUE THREAD

**Issue by Sicklou** [binafy/laravel-user-monitoring#35]
Hi,

I think there is an issue with packagist and composer.

I got the 1.0 version of the package, but there is no 'ajax_request' in the `VisitMonitoringMiddleware`.

The 1.0 is dated to  2023-08-07 09:38 UTC in packagist, but the release in github is from the 2023-08-29.

![image](https://github.com/binafy/laravel-user-monitoring/assets/8366863/7d7d08c6-5160-4f2f-b1a0-95bb5ae95bfc)

**Comment by milwad-dev** [comment]
Hi, because the new version of Laravel User Monitoring has `ajax_request` feature.
Please update the dependencies.
