### ISSUE TITLE
Problem to customize layout

### ISSUE THREAD

**Issue by Eudu4rdo** [binafy/laravel-user-monitoring#38]
Hi, firstly, congratulations on the work, I thought the lib was amazing!

I have problems to change base layout. I published views with ` php artisan vendor:publish --tag="laravel-user-monitoring-views` and edit, but when I reload page, nothing happens. Did I miss any steps?

Change exemple:
![image](https://github.com/binafy/laravel-user-monitoring/assets/56921645/198eb685-235e-4b82-bbaf-b9786bb11ef3)
Result (no change):
![image](https://github.com/binafy/laravel-user-monitoring/assets/56921645/37209406-b73b-448e-bdab-b2a974e06ceb)

**Comment by milwad-dev** [comment]
You just need to publish routes and change the controller with your view path:

```php
// routes/user-monitoring.php

Route::prefix('user-monitoring')->as('user-monitoring.')->group(function ($router) {
    // Visit Monitoring
    $router->get('visits-monitoring', [MyVisitController::class, 'index'])->name('visits-monitoring');
    $router->delete('visits-monitoring/{visitMonitoring}', [MyVisitController::class, 'destroy'])->name('visits-monitoring-delete');

  ...
});
```
