### ISSUE TITLE
Issue with view publish

### ISSUE THREAD

**Issue by AfzalSabbir** [binafy/laravel-user-monitoring#39]
No reflaction on change of published views.

**Comment by milwad-dev** [comment]
Could you explain more?

**Comment by AfzalSabbir** [comment]
I've publish views, and tried to make modification but changes were not showing.

**Comment by milwad-dev** [comment]
You can publish views and you need to create your controller!
But, we will add new features for editing the current views without needing an extra controller.

```
php artisan vendor:publish --tag="laravel-user-monitoring-views"
```

**Comment by AfzalSabbir** [comment]
`php artisan vendor:publish --tag="laravel-user-monitoring-views"`

Publishes in `resources/views/laravel-user-monitoring` but should be in `resources/views/vendor/LaravelUserMonitoring`.

Relocated in `resources/views/vendor/LaravelUserMonitoring`, works fine!
![image](https://github.com/binafy/laravel-user-monitoring/assets/39697431/b5afc51d-041e-4da6-99f4-9ca84afbe215)

And thanks for the package!
