### ISSUE TITLE
Problem saving data in action_monitoring table

### ISSUE THREAD

**Issue by Kamelhadj** [binafy/laravel-user-monitoring#41]
Hello everyone
After using this package on live laravel project i notice that some records missing some data like user_id and browser (unknown browser)
I hope you can help me figure it out
Thank you

**Comment by milwad-dev** [comment]
[If your browser is not `Chrome`, `Firefox` and ..., The `Laravel User Monitoring` return an [unknown browser](https://github.com/binafy/laravel-user-monitoring/blob/1.x/src/Utills/Detector.php#L12).
Also, if the user is not logged in, the user id will be null.
