### ISSUE TITLE
Using actionable trait creates unlimited records in database and ultimately crashes server with max execution

### ISSUE THREAD

**Issue by HamaadSaadAhsan** [binafy/laravel-user-monitoring#46]
![image](https://github.com/user-attachments/assets/a8722550-6aab-4942-99a4-bbab76bb13fb)

**Comment by milwad-dev** [comment]
The `Laravel User Monitoring` creates rows per read model, so you can turn off the read action:
https://github.com/binafy/laravel-user-monitoring?tab=readme-ov-file#action-monitoring
